"""QuecPython SMS API used by the EC600M firmware."""

from typing import Callable

SmsTextResult = tuple[str, str, int]
SmsPduResult = tuple[str, str]
SmsResult = SmsTextResult | int | None
PduResult = str | bytes | int | None
CallbackArgs = tuple[object, ...] | list[object]

def setSaveLoc(storage1: str, storage2: str, storage3: str) -> int: ...
def setCallback(callback: Callable[[CallbackArgs], None]) -> int: ...
def searchTextMsg(index: int) -> SmsResult: ...
def searchPduMsg(index: int) -> PduResult: ...
def getPduLength(pdu: str | bytes) -> int: ...
def decodePdu(pdu: str | bytes, length: int) -> SmsPduResult: ...
def deleteMsg(index: int, flag: int) -> int: ...
def sendTextMsg(phone_number: str, message: str, encoding: str) -> int: ...
