"""QuecPython voiceCall API used by the EC600M firmware."""

from typing import Callable

CallbackArgs = tuple[object, ...] | list[object]

def setCallback(callback: Callable[[CallbackArgs], None]) -> int: ...
def callStart(phone_number: str) -> int: ...
def callAnswer() -> int: ...
def callEnd() -> int: ...
def setVolume(volume: int) -> int: ...
def setChannel(channel: int) -> int: ...
