#pragma once
#define LV_CONF_H
#define LV_COLOR_DEPTH 16
#define LV_USE_OS LV_OS_NONE
#define LV_USE_STDLIB_MALLOC LV_STDLIB_CLIB
#define LV_USE_TINY_TTF 1
#define LV_TINY_TTF_FILE_SUPPORT 0
#define LV_USE_DRAW_SW 1
#define LV_USE_VECTOR_GRAPHIC 1
#define LV_USE_MATRIX 1
#define LV_USE_FLOAT 1
#define LV_USE_SVG 1
#define LV_USE_THORVG 1
#define LV_USE_THORVG_INTERNAL 1
#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_BUILD_EXAMPLES 0
#define LV_BUILD_DEMOS 0
