"""Minimal pyserial surface used by the firmware deployment CLI."""

class Serial:
    port: str

    def __init__(self, port: str, baudrate: int, timeout: float) -> None: ...
    def close(self) -> None: ...
    def reset_input_buffer(self) -> None: ...
    def reset_output_buffer(self) -> None: ...
    def write(self, data: bytes) -> int: ...
    def read_until(self, expected: bytes) -> bytes: ...
    def read(self, size: int = ...) -> bytes: ...
